<a href="https://colab.research.google.com/github/Ashikur-ai/Learn-Machine-Learning/blob/main/16_Working_with_Columns_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd

In [20]:
from numpy.random import randn
np.random.seed(101)

In [21]:
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [23]:
df = pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns=['W', 'X', 'Y', 'Z'])

In [24]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [25]:
index = 'A, B, C, D, E'.split(',')

In [26]:
index

['A', ' B', ' C', ' D', ' E']

#Showing Columns

In [31]:
df1 = df[['W', 'Y']]
df1

          W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579
C  2.154846 -0.755325
D  0.147027  0.558769
E -0.925874 -1.133817

#Create a new DataFrame

In [32]:
df1['X1'] = df['X']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [33]:
df1

          W         Y        X1
A -0.993263 -1.136645  0.196800
B  1.025984 -0.031579 -0.156598
C  2.154846 -0.755325 -0.610259
D  0.147027  0.558769 -0.479448
E -0.925874 -1.133817  1.862864

#Remove a column from DataFrame

In [34]:
df1.drop('X1', axis=1)

          W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579
C  2.154846 -0.755325
D  0.147027  0.558769
E -0.925874 -1.133817

In [35]:
df1

          W         Y        X1
A -0.993263 -1.136645  0.196800
B  1.025984 -0.031579 -0.156598
C  2.154846 -0.755325 -0.610259
D  0.147027  0.558769 -0.479448
E -0.925874 -1.133817  1.862864

# That was just for one time. Forever Delete use this process

In [36]:
df1.drop('X1', axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [37]:
df1

          W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579
C  2.154846 -0.755325
D  0.147027  0.558769
E -0.925874 -1.133817

#Remove a Row

In [38]:
df1.drop('E', axis=0)

          W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579
C  2.154846 -0.755325
D  0.147027  0.558769

In [39]:
df1

          W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579
C  2.154846 -0.755325
D  0.147027  0.558769
E -0.925874 -1.133817