<a href="https://colab.research.google.com/github/Ashikur-ai/Learn-Machine-Learning/blob/main/17_Working_with_Rows_Indexing_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import randn
np.random.seed(101)

In [3]:
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [4]:
df = pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns=['W', 'X', 'Y', 'Z'])

In [5]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

#Selection of Row

In [6]:
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [7]:
df.iloc[3]

W   -0.497104
X   -0.754070
Y   -0.943406
Z    0.484752
Name: D, dtype: float64

#One single element

In [8]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [9]:
df.loc['D', 'W']

-0.49710402288933153

In [10]:
df.loc[['A', 'B'], ['W', 'X']]

          W         X
A  0.302665  1.693723
B -0.134841  0.390528

#Conditional Search

In [11]:
df>0

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [12]:
df[df>0]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [13]:
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [14]:
df[df['W']>0]['Y']

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [15]:
df[(df['W']>0) | (df['Y']>0)]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
E -0.116773  1.901755  0.238127  1.996652

In [16]:
df[(df['W']>0) & (df['Y']>0)]

          W        X         Y         Z
C  0.807706  0.07296  0.638787  0.329646