<a href="https://colab.research.google.com/github/Ashikur-ai/Learn-Machine-Learning/blob/main/18_How_to_reset_index_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import randn
np.random.seed(101)

In [3]:
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [4]:
df = pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns=['W', 'X', 'Y', 'Z'])

In [5]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

#Reset index

In [17]:
df.reset_index()

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [18]:
a = ['a', 'b', 'c', 'd', 'e']

In [19]:
df['NEW'] = a

In [23]:
df.set_index('NEW', inplace=True)

In [24]:
  df

            W         X         Y         Z
NEW
a    0.302665  1.693723 -1.706086 -1.159119
b   -0.134841  0.390528  0.166905  0.184502
c    0.807706  0.072960  0.638787  0.329646
d   -0.497104 -0.754070 -0.943406  0.484752
e   -0.116773  1.901755  0.238127  1.996652