<a href="https://colab.research.google.com/github/Ashikur-ai/Learn-Machine-Learning/blob/main/19_How_to_handle_missing_data_in_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import randn
np.random.seed(101)

In [28]:
df = pd.DataFrame({'A':[1, 2, np.nan, np.nan], 'B':[2, 8, np.nan, 5], 'C':[1, 3, 5, 7]})

In [29]:
df

     A    B  C
0  1.0  2.0  1
1  2.0  8.0  3
2  NaN  NaN  5
3  NaN  5.0  7

In [30]:
df.dropna()

     A    B  C
0  1.0  2.0  1
1  2.0  8.0  3

In [31]:
df.dropna(axis=1)

   C
0  1
1  3
2  5
3  7

In [32]:
df>2

       A      B      C
0  False  False  False
1  False   True   True
2  False  False   True
3  False   True   True

In [33]:
df[df>2]

    A    B    C
0 NaN  NaN  NaN
1 NaN  8.0  3.0
2 NaN  NaN  5.0
3 NaN  5.0  7.0

In [34]:
df

     A    B  C
0  1.0  2.0  1
1  2.0  8.0  3
2  NaN  NaN  5
3  NaN  5.0  7

In [36]:
df.fillna(value=0)

     A    B  C
0  1.0  2.0  1
1  2.0  8.0  3
2  0.0  0.0  5
3  0.0  5.0  7

In [37]:
df.fillna(value=df['A'].mean())

     A    B  C
0  1.0  2.0  1
1  2.0  8.0  3
2  1.5  1.5  5
3  1.5  5.0  7